config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "invitations/new"
    get "invitations/create"
  end
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/, defaults: { locale: "ka" } do
    root "words#index"
    resources :words, only: [ :index, :show ]
    namespace :admin do
      root to: "words#index"
      resources :invitations, only: [ :new, :create ]
      resources :words
      resources :recently_deleted_words, only: [ :index, :update ]
      resources :short_forms, only: [ :index ]
      resources :other_qualifications
      get "xlsx_exports/words", to: "xlsx_exports#words"
    end
  end
end

app/models/other_qualification.rb
# == Schema Information
#
# Table name: other_qualifications
#
#  id            :bigint           not null, primary key
#  deleted_at    :datetime
#  en_name       :string
#  en_short_name :string
#  name          :string           not null
#  short_name    :string           not null
#
# Indexes
#
#  index_other_qualifications_on_deleted_at  (deleted_at)
#  index_other_qualifications_on_name        (name) UNIQUE
#  index_other_qualifications_on_short_name  (short_name) UNIQUE
#
class OtherQualification < ApplicationRecord
  include SoftDeletable
  validates :name, :short_name, presence: true
end

app/controllers/admin/other_qualifications_controller.rb
module Admin
  class OtherQualificationsController < ::Admin::BaseController
    def index
      @other_qualifications = OtherQualification.all
    end

    def show
      @other_qualification = OtherQualification.find(params[:id])
    end

    def new
      @other_qualification = OtherQualification.new
    end

    def edit
      @other_qualification = OtherQualification.find(params[:id])
    end

    def create
      @other_qualification = OtherQualification.new(other_qualification_params)
      if @other_qualification.save
        redirect_to admin_other_qualifications_path, notice: I18n.t("admin.other_qualifications.create_notice")
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      @other_qualification = OtherQualification.find(params[:id])
      if @other_qualification.update(other_qualification_params)
        redirect_to admin_other_qualifications_path, notice: I18n.t("admin.other_qualifications.update_notice")
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @other_qualification = OtherQualification.find(params[:id])

      redirect_to admin_other_qualifications_path, notice: @other_qualification.soft_delete ? I18n.t("admin.other_qualifications.delete_notice") : I18n.t("admin.other_qualifications.delete_error")
    end

    private

    def other_qualification_params
      params.require(:other_qualification).permit(:short_name, :name, :en_name, :en_short_name)
    end
  end
end

app/views/admin/other_qualifications/_form.html.erb
<% if @other_qualification.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @other_qualification.errors.full_messages.each do |message| %>
        <li class="text-red-500"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @other_qualification] do |f| %>
  <div class="block m-6 w-1/2">
    <%= f.label :short_name, "მოკლე აღნიშვნა", class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :short_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="block m-6 w-1/2">
    <%= f.label :name, "სრული აღნიშვნა", class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="block m-6 w-1/2">
    <%= f.label :en_short_name, "ინგლისური მოკლე აღნიშვნა", class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :en_short_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <div class="block m-6 w-1/2">
    <%= f.label :en_name, "ინგლისური სრული აღნიშვნა", class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= f.text_field :en_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="block m-6">
    <%= f.submit t('admin.words.submit'), class: "text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </div>
<% end %>

app/views/admin/other_qualifications/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/other_qualifications/index.html.erb
<div id="words-section" class="mx-6 mt-4">
  <div>
    <%= link_to t('admin.other_qualifications.new_button'), new_admin_other_qualification_path, class: "btn-primary" %>
  </div>
  <table class="mt-4">
  <thead>
    <tr>
      <td class="border border-2 px-4 py-2 text-gray-500">მოკლე აღნიშვნა</td>
      <td class="border border-2 px-4 py-2 text-gray-500">სრული აღნიშვნა</td>
      <td class="border border-2 px-4 py-2 text-gray-500">ინგლისური მოკლე აღნიშვნა</td>
      <td class="border border-2 px-4 py-2 text-gray-500">ინგლისური სრული აღნიშვნა</td>
      <td class="border border-2 px-4 py-2 text-gray-500">მოქმედება</td>
    </tr>
  </thead>
    <tbody>
      <% @other_qualifications.each do |other_qualification| %>
        <tr>
          <td class="border border-2 px-4 py-2"><%= other_qualification.short_name %></td>
          <td class="border border-2 px-4 py-2"><%= other_qualification.name %></td>
          <td class="border border-2 px-4 py-2"><%= other_qualification.en_short_name %></td>
          <td class="border border-2 px-4 py-2"><%= other_qualification.en_name %></td>
          <td class="border border-2 px-4 py-2">
            <div class="flex gap-1 items-center">
              <%= link_to 'რედაქტირება', edit_admin_other_qualification_path(other_qualification), class: "text-[#555] hover:text-black bg-neo p-2 rounded rounded-lg" %>
              <%= button_to 'წაშლა', admin_other_qualification_path(other_qualification), method: :delete, class: "text-[#555] hover:text-black bg-gray-300 p-2 rounded rounded-lg" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/other_qualifications/new.html.erb
<%= render partial: 'form' %>