config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "invitations/new"
    get "invitations/create"
  end
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/, defaults: { locale: "ka" } do
    root "words#index"
    resources :words, only: [ :index, :show ]
    namespace :admin do
      root to: "words#index"
      resources :invitations, only: [ :new, :create ]
      resources :words
      resources :recently_deleted_words, only: [ :index, :update ]
      resources :short_forms, only: [ :index ]
      resources :other_qualifications
      get "xlsx_exports/words", to: "xlsx_exports#words"
    end
  end
end

app/controllers/admin/invitations_controller.rb
module Admin
  class InvitationsController < ApplicationController
    before_action :authenticate_user!

    def new
      @user = User.new
    end

    def create
      @user = User.invite!(email: params[:email])

      if @user.errors.empty?
        redirect_to admin_root_path, notice: "Invitation sent successfully."
      else
        flash.now[:alert] = "Failed to send invitation."
        render :new
      end
    end
  end
end

app/helpers/admin/invitations_helper.rb
module Admin::InvitationsHelper
end

app/views/admin/invitations/new.html.erb
<div class="p-10">
<h1 class="mb-5 text-xl font-bold"><%= t(".invite_user") %></h1>

<%= form_with url: admin_invitations_path, local: true do |f| %>
  <div class="flex gap-2">
    <%= f.label t(".email") %>
    <%= f.email_field :email, required: true, class: "ring-neo-dark ring-2 rounded" %>
  </div>

  <div class="flex gap-2 mt-5">
    <%= link_to t("shared.back"), admin_root_path, class: "text-black bg-neo hover:bg-neo-hover focus:ring-4 focus:outline-none focus:ring-neo font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <%= f.submit t(".send_invitation"), class: "btn-primary" %>
  </div>
<% end %>
</div>