config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "invitations/new"
    get "invitations/create"
  end
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/, defaults: { locale: "ka" } do
    root "words#index"
    resources :words, only: [ :index, :show ]
    namespace :admin do
      root to: "words#index"
      resources :invitations, only: [ :new, :create ]
      resources :words
      resources :recently_deleted_words, only: [ :index, :update ]
      resources :short_forms, only: [ :index ]
      resources :other_qualifications
      get "xlsx_exports/words", to: "xlsx_exports#words"
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || t('admin.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/neo.png" type="image/png">
    <link rel="apple-touch-icon" href="/neo.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css", media: "all", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js@11.1.0/public/assets/styles/choices.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/choices.js@11.1.0/public/assets/scripts/choices.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <nav class="px-8 py-4 flex items-center justify-between bg-[#e0ecf9]">
      <div class="flex items-center">
        <%= image_tag '/neo.png', class: 'h-16 md:h-24' %>
        <%= link_to t('admin.title'), admin_root_path, class: "ml-2 md:ml-8 text-lg md:text-3xl text-neo-dark" %>
      </div>
      <div class="flex items-center">
        <%= link_to t('admin.navbar.invite_user'), new_admin_invitation_path, class: "ml-2 md:ml-8 text-neo-dark" %>
        <%= link_to t('admin.navbar.other_qualifications'), admin_other_qualifications_path, class: "ml-2 md:ml-8 text-neo-dark" %>
        <%= link_to url_for(params.as_json.merge(locale: (I18n.available_locales - [I18n.locale]).first)), class: "text-neo-dark", data: { turbo: false } do %>
          <%= image_tag "#{ (I18n.available_locales - [I18n.locale]).first }.svg", class: "rounded rounded-lg border border-white border-2 max-w-8 max-h-8 ml-2 md:ml-8", width: 32, height: 32 %>
        <% end %>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="w-full p-2 bg-green-200 text-center">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="w-full p-2 bg-red-200 text-center">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || t('app.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/neo.png" type="image/png">
    <link rel="apple-touch-icon" href="/neo.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 flex flex-col h-screen">
    <nav class="px-8 py-4 flex items-center justify-between bg-[#e0ecf9]">
      <div class="flex items-center">
        <%= image_tag '/neo.png', class: 'h-16 md:h-24' %>
        <%= link_to t('app.title'), root_path(locale: I18n.locale), class: "ml-2 md:ml-8 text-lg md:text-3xl text-neo-dark font-nino" %>
      </div>
      <div class="flex items-center gap-6">
        <a href="#" class="text-neo-dark text-sm md:text-lg font-bold font-nino text-right"><%= t("app.navbar.about_us") %></a>
        <%= link_to url_for(params.as_json.merge(locale: (I18n.available_locales - [I18n.locale]).first)), class: "text-neo-dark", data: { turbo: false } do %>
          <%= image_tag "#{ (I18n.available_locales - [I18n.locale]).first }.svg", class: "rounded rounded-lg border border-white border-2", width: 32, height: 32 %>
        <% end %>
      </div>
    </nav>
    <main class="flex-1">
      <%= yield %>
    </main>
    <footer class="w-full bg-neo mt-8 py-6 flex flex-col">
      <div class="px-6 flex justify-center">
        <%= link_to 'https://lexicography.iliauni.edu.ge/', class: 'px-6' do %>
          <%= image_tag 'ISU-lexicography.png', alt: 'Ilia State University Lexicography Logo', class: 'h-16' %>
        <% end %>
        <%= link_to 'https://iliauni.edu.ge/' , class: 'px-6' do %>
          <%= image_tag 'ISU.png', alt: 'Ilia State University Logo', class: 'h-16' %>
        <% end %>
        <%= link_to 'https://unilab.iliauni.edu.ge/' , class: 'px-6' do %>
          <%= image_tag 'unilab.png', alt: 'unilab logo', class: 'h-16' %>
        <% end %>
        <%= link_to 'https://www.rustaveli.org.ge/' , class: 'px-6' do %>
          <%= image_tag 'rustaveli-logo.png', alt: 'rustaveli logo', class: 'h-16' %>
        <% end %>
      </div>
      <p class="text-center text-sm mt-4">© <%= Time.zone.today.year %></p>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50">
<head>
  <title><%= content_for(:title) || "Neo Dict" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/neo.png" type="image/png">
  <link rel="apple-touch-icon" href="/neo.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-gray-100">
<%= content_tag :p, notice, class: 'text-green-500 bg-green-200 py-2 px-4 text-center' if notice %>
<%= content_tag :p, alert, class: 'text-red-500 bg-red-200 py-2 px-4 text-center' if alert %>
<%= yield %>
</body>
</html>